In [1]:
import torch

In [2]:
x=torch.tensor((5,3))
y=torch.tensor((2,1))

In [4]:
print(x*y)

tensor([10,  3])


In [5]:
x=torch.zeros((2,3))

In [8]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
print(x.shape)

torch.Size([2, 3])


In [10]:
y=torch.rand((2,3))

In [11]:
print(y)

tensor([[0.3403, 0.7504, 0.2876],
        [0.5956, 0.3722, 0.5293]])


In [12]:
z= y.view((3,2))

In [13]:
print(z)

tensor([[0.3403, 0.7504],
        [0.2876, 0.5956],
        [0.3722, 0.5293]])
